services:
    Recognize\ApiBundle\EventListener\JsonRequestTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

    Recognize\ApiBundle\EventListener\JSONAnnotationSubscriber:
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            $environment: '%kernel.environment%'
